CREATE TABLE INFRA_ASSET_DETAILS (
    ASSET_ID VARCHAR PRIMARY KEY,  -- <-- Added Primary Key
    ASSET_TAG VARCHAR,
    ASSET_NAME VARCHAR,
    ASSET_SERIAL VARCHAR,
    MODEL_NAME VARCHAR,
    MODEL_NUMBER VARCHAR,
    MANUFACTURER_NAME VARCHAR,
    CATEGORY_NAME VARCHAR,
    CATEGORY_TYPE VARCHAR,
    STATUS_NAME VARCHAR,
    STATUS_DEPLOYABLE NUMBER,
    STATUS_PENDING NUMBER,
    STATUS_ARCHIVED NUMBER,
    STATUS_NOTES VARCHAR,
    ASSET_ASSIGNED_TO VARCHAR(16777216),
    ASSET_USER_ID VARCHAR,
    USER_EMAIL VARCHAR,
    FULL_NAME VARCHAR,
    USERNAME VARCHAR,
    SUPPLIER_ID VARCHAR,
    SUPPLIER_NAME VARCHAR,
    COMPANY_ID VARCHAR,
    COMPANY_NAME VARCHAR,
    ASSET_PURCHASE_DATE DATE,
    ASSET_EOL_DATE DATE,
    ASSET_EOL_EXPLICIT NUMBER,
    ASSET_LAST_AUDIT_DATE DATE,
    ASSET_NEXT_AUDIT_DATE DATE,
    ASSET_PHYSICAL NUMBER,
    ASSET_BYOD NUMBER,
    SNIPEIT_CPU_7 VARCHAR,
    SNIPEIT_RAM_8 VARCHAR,
    SNIPEIT_DISK_TYPE_9 VARCHAR,
    SNIPEIT_DISK_SIZE_10 VARCHAR,
    SNIPEIT_DISPLAY_SIZE_11 VARCHAR,
    SNIPEIT_RESOLUTION_13 VARCHAR,
    SNIPEIT_MONITOR_TYPE_14 VARCHAR,
    SNIPEIT_REPAIR_COUNT_15 NUMBER,
    ASSET_CHECKIN_COUNTER NUMBER,
    ASSET_CHECKOUT_COUNTER NUMBER,
    ASSET_REQUESTS_COUNTER NUMBER,
    ASSET_NOTES VARCHAR,

    -- Foreign Key References
    CONSTRAINT fk_asset_user_id FOREIGN KEY (ASSET_USER_ID) 
        REFERENCES USERS(USER_ID),
    CONSTRAINT fk_supplier_id FOREIGN KEY (SUPPLIER_ID) 
        REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT fk_company_id FOREIGN KEY (COMPANY_ID) 
        REFERENCES COMPANIES(COMPANY_ID)
);


CREATE TABLE INFRA_ASSET_ACTION_LOGS (
    LOG_ID VARCHAR PRIMARY KEY,  -- <-- Added Primary Key
    ASSET_ID VARCHAR(16777216),
    ACTION_TYPE VARCHAR(16777216),
    ASSET_ASSIGNED_TO VARCHAR(16777216),
    ACTION_NOTE VARCHAR(16777216),
    ACTION_LOG_META VARCHAR(16777216),
    ACTION_DATE TIMESTAMP_NTZ(9),
    ACTION_CREATED_AT TIMESTAMP_NTZ(9),
    ACTION_UPDATED_AT TIMESTAMP_NTZ(9),
    ACTION_DELETED_AT TIMESTAMP_NTZ(9),
    
    -- Foreign Key References
    CONSTRAINT fk_asset_id FOREIGN KEY (ASSET_ID) 
        REFERENCES INFRA_ASSET_DETAILS(ASSET_ID),
    CONSTRAINT fk_assigned_to FOREIGN KEY (ASSET_ASSIGNED_TO) 
        REFERENCES INFRA_ASSET_DETAILS(ASSET_ASSIGNED_TO)
);


