create or replace TABLE INFRA_DB.INFRA_SCHEMA.INFRA_ASSET_DETAILS (
	ASSET_ID NUMBER(38,0) COMMENT 'Asset ID',
	ASSET_TAG VARCHAR(16777216) COMMENT 'Unique identifier for the asset',
	ASSET_NAME VARCHAR(16777216) COMMENT 'Name of the asset',
	ASSET_SERIAL VARCHAR(16777216) COMMENT 'Serial number of the asset',
	MODEL_NAME VARCHAR(16777216) COMMENT 'Name of the model associated with the asset',
	MODEL_NUMBER VARCHAR(16777216) COMMENT 'Model number of the asset',
	MANUFACTURER_NAME VARCHAR(16777216) COMMENT 'Name of the manufacturer of the asset',
	CATEGORY_NAME VARCHAR(16777216) COMMENT 'Category name of the asset',
	CATEGORY_TYPE VARCHAR(16777216) COMMENT 'Category type of the asset',
	STATUS_NAME VARCHAR(16777216) COMMENT 'Name of the asset status',
	STATUS_DEPLOYABLE NUMBER(38,0) COMMENT 'Indicates whether the asset is deployable',
	STATUS_PENDING NUMBER(38,0) COMMENT 'Indicates whether the asset is pending',
	STATUS_ARCHIVED NUMBER(38,0) COMMENT 'Indicates whether the asset is archived',
	STATUS_NOTES VARCHAR(16777216) COMMENT 'Additional notes on the asset status',
	ASSET_ASSIGNED_TO VARCHAR(16777216) COMMENT 'ID of the user to whom the asset is assigned',
	ASSET_USER_ID VARCHAR(16777216) COMMENT 'User ID associated with the asset',
	USER_EMAIL VARCHAR(16777216) COMMENT 'Email address of the assigned user',
	FULL_NAME VARCHAR(16777216) COMMENT 'Full name of the assigned user',
	USERNAME VARCHAR(16777216) COMMENT 'Username of the assigned user',
	SUPPLIER_ID VARCHAR(16777216) COMMENT 'ID of the supplier who provided the asset',
	SUPPLIER_NAME VARCHAR(16777216) COMMENT 'Name of the supplier',
	COMPANY_ID VARCHAR(16777216) COMMENT 'ID of the company owning the asset',
	COMPANY_NAME VARCHAR(16777216) COMMENT 'Name of the company',
	ASSET_PURCHASE_DATE DATE COMMENT 'Purchase date of the asset',
	ASSET_EOL_DATE DATE COMMENT 'End of life date for the asset',
	ASSET_EOL_EXPLICIT NUMBER(38,0) COMMENT 'Indicates if EOL is explicitly set',
	ASSET_LAST_AUDIT_DATE DATE COMMENT 'Date of the last audit for the asset',
	ASSET_NEXT_AUDIT_DATE DATE COMMENT 'Date for the next scheduled audit',
	ASSET_PHYSICAL NUMBER(38,0) COMMENT 'Indicates if the asset is physical',
	ASSET_BYOD NUMBER(38,0) COMMENT 'Indicates if the asset is BYOD (Bring Your Own Device)',
	SNIPEIT_CPU_7 VARCHAR(16777216) COMMENT 'CPU specification of the asset',
	SNIPEIT_RAM_8 VARCHAR(16777216) COMMENT 'RAM size of the asset',
	SNIPEIT_DISK_TYPE_9 VARCHAR(16777216) COMMENT 'Disk type of the asset',
	SNIPEIT_DISK_SIZE_10 VARCHAR(16777216) COMMENT 'Disk size of the asset',
	SNIPEIT_DISPLAY_SIZE_11 VARCHAR(16777216) COMMENT 'Display size of the asset',
	SNIPEIT_RESOLUTION_13 VARCHAR(16777216) COMMENT 'Resolution of the asset',
	SNIPEIT_MONITOR_TYPE_14 VARCHAR(16777216) COMMENT 'Monitor type of the asset',
	SNIPEIT_REPAIR_COUNT_15 NUMBER(38,0) COMMENT 'Number of repairs done on the asset',
	ASSET_CHECKIN_COUNTER NUMBER(38,0) COMMENT 'Counter for asset check-ins',
	ASSET_CHECKOUT_COUNTER NUMBER(38,0) COMMENT 'Counter for asset check-outs',
	ASSET_REQUESTS_COUNTER NUMBER(38,0) COMMENT 'Counter for asset requests',
	ASSET_NOTES VARCHAR(16777216) COMMENT 'Additional notes or comments related to the asset'
);